version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - .:/var/www/html
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      - logger

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
    networks:
      - logger

  php:
    build:
      ./docker/php
    working_dir: /var/www/html/public/
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb
    networks:
      - logger

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - logger

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mariadb
    networks:
      - logger

networks:
  logger:
    driver: bridge